In [106]:
import numpy as np 
import sklearn
import sklearn.model_selection

inputs = [] 
labels = []
with open("seeds_dataset.txt", "r") as f:
    for line in f:
        inputs.append([float(val) for val in line.strip().split()[:7]])
        labels.append(int(line.strip().split()[7]))

inputs = np.array(inputs, dtype=float)
labels = np.array(labels)
max_val = np.max(inputs)

x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(inputs, labels, train_size=0.8, shuffle=True)
x_train = x_train / max_val
x_test = x_test / max_val

In [108]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def relu(x):
    return np.maximum(0, x)

def sigmoid_derivative(x):
    sigmoid_x = 1 / (1 + np.exp(-x))
    return sigmoid_x * (1 - sigmoid_x)

def relu_derivative(x):
    return np.where(x > 0, 1, 0)

def mean_squared_error(output, expected_label):
    expected = np.zeros(3)
    expected[expected_label - 1] = 1.0
    print(output, expected)

    return 1 / 2 * np.sum((expected - output) ** 2)

class Layer:
    def __init__(self, m, n, activation):
        #n - nr de neuroni de pe stratul x
        #m - nr de neuroni de pe stratul x - 1
        self.matrix = np.random.rand(n, m)
        self.activation = activation
    
    def activate(self, neurons):
        output = []
        for neuron in neurons:
            output.append(self.activation(neuron))
        return np.array(output) 

alfa = 0.01 #learning rate
epochs = 10

# 2 straturi ascunse de cate 5 neuroni fiecare.
# Activare - ReLU pe straturile ascunse, Sigmoid pe cel de output
layers = [Layer(7, 5, relu), Layer(5, 5, relu), Layer(5, 3, sigmoid)]

In [116]:
def compute_output(input, layer):
    output = np.dot(layer.matrix, input)
    return layer.activate(output)

def feed_forward(input, label, layers):
    output = None
    for layer in layers:
        print(input)
        output = compute_output(input, layer)
        input = output
    print(output)
    print(f"MSE: {mean_squared_error(output, label)}")

feed_forward(x_train[5], y_train[5], layers)

[0.67705382 0.67847025 0.04119924 0.26581681 0.15061379 0.06199245
 0.24315392]
[1.56077003 1.10196043 0.852695   1.23863542 0.60598857]
[2.07669807 3.24708953 2.35069905 4.14987464 2.63522775]
[0.99980945 0.99985221 0.99821526]
[0.99980945 0.99985221 0.99821526] [1. 0. 0.]
MSE: 0.9980690946262576
